# Generated by Django 5.0.3 on 2024-10-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievementemployee",
            name="achievement_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
