# Generated by Django 5.0.3 on 2024-10-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_alter_achievementemployee_achievement_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievementemployee",
            name="achievement_date",
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
