# Generated by Django 5.0.3 on 2024-10-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_remove_achievementemployee_achievement_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementemployee",
            name="achievement_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
